routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//首页
Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

//个人中心
Route::get('/home', 'HomeController@index')->name('home');

//常用信息
Route::prefix('info')->name('info.')->group(function () {
    Route::get('/', 'InfoController@index')->name('index');
    Route::get('buy', 'InfoController@buy')->name('buy');
    Route::get('zb', 'InfoController@zb')->name('zb');
});

Route::middleware('auth')->group(function () {
    //地址管理
    Route::prefix('address')->name('address.')->group(function () {
        Route::get('/', 'AddressController@index')->name('index');
        Route::post('store', 'AddressController@store')->name('store');
        Route::delete('destroy/{id}', 'AddressController@destroy')->name('destroy');
    });

    //订单管理
    Route::prefix('order')->name('order.')->group(function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('create/{mall_id}', 'OrderController@create')->name('create');
        Route::post('store', 'OrderController@store')->name('store');
        Route::get('show/{id}', 'OrderController@show')->name('show');
        Route::post('success/{id}', 'OrderController@success')->name('success');
        Route::delete('destroy/{id}', 'OrderController@destroy')->name('destroy');
        Route::get('export_order/{id}', 'OrderController@export_order')->middleware('admin')->name('export_order');
    });
    //购物车
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::get('/{mall_id}', 'CartController@index')->name('index');
        Route::post('store', 'CartController@store')->name('store');
        Route::delete('destroy/{id}', 'CartController@destroy')->name('destroy');
    });
    //建议留言
    Route::prefix('message')->name('message.')->group(function () {
        Route::get('/', 'MessageController@index')->name('index')->middleware('admin');
        Route::get('create', 'MessageController@create')->name('create');
        Route::post('store', 'MessageController@store')->name('store');
        Route::delete('destroy/{id}', 'MessageController@destroy')->name('destroy')->middleware('s_admin');
    });
});

//后台管理
Route::prefix('admin')->middleware('auth', 'admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create/{mall_id}', 'AdminController@create')->name('create');
    Route::post('store', 'AdminController@store')->name('store');
    Route::get('edit/{mall_id}/{id}', 'AdminController@edit')->name('edit');
    Route::put('update/{id}', 'AdminController@update')->name('update');
    Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
    Route::post('pay', 'AdminController@pay')->name('pay');
    Route::post('pay_back', 'AdminController@pay_back')->name('pay_back');
    Route::get('product/{mall_id}', 'AdminController@product')->name('product');
    Route::get('order/{mall_id}', 'AdminController@order')->name('order');
    Route::post('trigger/{id}', 'AdminController@trigger')->name('trigger');
    Route::get('total_order/{mall_id}', 'AdminController@total_order')->name('total_order');
    Route::put('putaway/{id}', 'AdminController@putaway')->name('putaway');
    //订单回收站
    Route::prefix('recycle')->name('recycle.')->group(function () {
        Route::get('/{mall_id}', 'OrderRecycleController@index')->name('index');
        Route::post('back_order', 'OrderRecycleController@back_order')->name('back_order');
        Route::delete('destroy', 'OrderRecycleController@destroy')->name('destroy');
    });

    //以下操作需要超级管理员权限
    Route::middleware('s_admin')->group(function () {
        //清除所有缓存
        Route::get('clear_cache', 'AdminController@clear_cache')->name('clear_cache');
        //消费排行
        Route::get('buytop', 'AdminController@buytop')->name('buytop');


        //用户管理
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'UserController@index')->name('index');
            Route::get('edit/{id}', 'UserController@edit')->name('edit');
            Route::put('update/{id}', 'UserController@update')->name('update');
        });

        //用户记录管理
        Route::prefix('userlog')->name('userlog.')->group(function () {
            Route::get('/', 'UserLogController@index')->name('index');
        });

        //特殊群体管理
        Route::prefix('aged')->name('aged.')->group(function () {
            Route::get('/', 'AgedController@index')->name('index');
            Route::get('edit/{id}', 'AgedController@edit')->name('edit');
            Route::put('update/{id}', 'AgedController@update')->name('update');
            Route::get('create', 'AgedController@create')->name('create');
            Route::post('store', 'AgedController@store')->name('store');
            Route::delete('destroy/{id}', 'AgedController@destroy')->name('destroy');
        });

        //商户管理
        Route::prefix('mall')->name('mall.')->group(function () {
            Route::get('/', 'MallController@index')->name('index');
            Route::get('edit/{id}', 'MallController@edit')->name('edit');
            Route::put('update/{id}', 'MallController@update')->name('update');
        });
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6" >
                @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                @endif
                <ul class="list-group">
                    <li class="list-group-item active">个人中心</li>
                    <a href="{{ route('address.index') }}">
                        <li class="list-group-item">收货信息管理</li>
                    </a>
                    @foreach($malls as $mall)
                    <a href="{{ route('order.create',$mall->id) }}">
                        <li class="list-group-item">开始购物[{{ $mall->name }}]</li>
                    </a>
                    @endforeach
                    <a href="{{ route('order.index') }}">
                        <li class="list-group-item">我的订单</li>
                    </a>
                    <a href="{{ route('message.create') }}">
                        <li class="list-group-item">建议&留言</li>
                    </a>
                    @if(Auth()->check())
                        @if(Auth()->user()->is_admin!=='0')
                            <a href="{{ route('admin.index') }}">
                                <li class="list-group-item">管理入口</li>
                            </a>
                        @endif
                    @endif
                </ul>

            </div>
        </div>
    </div>
@endsection