routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//首页
Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

//个人中心
Route::get('/home', 'HomeController@index')->name('home');

//常用信息
Route::prefix('info')->name('info.')->group(function () {
    Route::get('/', 'InfoController@index')->name('index');
    Route::get('buy', 'InfoController@buy')->name('buy');
    Route::get('zb', 'InfoController@zb')->name('zb');
});

Route::middleware('auth')->group(function () {
    //地址管理
    Route::prefix('address')->name('address.')->group(function () {
        Route::get('/', 'AddressController@index')->name('index');
        Route::post('store', 'AddressController@store')->name('store');
        Route::delete('destroy/{id}', 'AddressController@destroy')->name('destroy');
    });

    //订单管理
    Route::prefix('order')->name('order.')->group(function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('create/{mall_id}', 'OrderController@create')->name('create');
        Route::post('store', 'OrderController@store')->name('store');
        Route::get('show/{id}', 'OrderController@show')->name('show');
        Route::post('success/{id}', 'OrderController@success')->name('success');
        Route::delete('destroy/{id}', 'OrderController@destroy')->name('destroy');
        Route::get('export_order/{id}', 'OrderController@export_order')->middleware('admin')->name('export_order');
    });
    //购物车
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::get('/{mall_id}', 'CartController@index')->name('index');
        Route::post('store', 'CartController@store')->name('store');
        Route::delete('destroy/{id}', 'CartController@destroy')->name('destroy');
    });
    //建议留言
    Route::prefix('message')->name('message.')->group(function () {
        Route::get('/', 'MessageController@index')->name('index')->middleware('admin');
        Route::get('create', 'MessageController@create')->name('create');
        Route::post('store', 'MessageController@store')->name('store');
        Route::delete('destroy/{id}', 'MessageController@destroy')->name('destroy')->middleware('s_admin');
    });
});

//后台管理
Route::prefix('admin')->middleware('auth', 'admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create/{mall_id}', 'AdminController@create')->name('create');
    Route::post('store', 'AdminController@store')->name('store');
    Route::get('edit/{mall_id}/{id}', 'AdminController@edit')->name('edit');
    Route::put('update/{id}', 'AdminController@update')->name('update');
    Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
    Route::post('pay', 'AdminController@pay')->name('pay');
    Route::post('pay_back', 'AdminController@pay_back')->name('pay_back');
    Route::get('product/{mall_id}', 'AdminController@product')->name('product');
    Route::get('order/{mall_id}', 'AdminController@order')->name('order');
    Route::post('trigger/{id}', 'AdminController@trigger')->name('trigger');
    Route::get('total_order/{mall_id}', 'AdminController@total_order')->name('total_order');
    Route::put('putaway/{id}', 'AdminController@putaway')->name('putaway');
    //订单回收站
    Route::prefix('recycle')->name('recycle.')->group(function () {
        Route::get('/{mall_id}', 'OrderRecycleController@index')->name('index');
        Route::post('back_order', 'OrderRecycleController@back_order')->name('back_order');
        Route::delete('destroy', 'OrderRecycleController@destroy')->name('destroy');
    });

    //以下操作需要超级管理员权限
    Route::middleware('s_admin')->group(function () {
        //清除所有缓存
        Route::get('clear_cache', 'AdminController@clear_cache')->name('clear_cache');
        //消费排行
        Route::get('buytop', 'AdminController@buytop')->name('buytop');


        //用户管理
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'UserController@index')->name('index');
            Route::get('edit/{id}', 'UserController@edit')->name('edit');
            Route::put('update/{id}', 'UserController@update')->name('update');
        });

        //用户记录管理
        Route::prefix('userlog')->name('userlog.')->group(function () {
            Route::get('/', 'UserLogController@index')->name('index');
        });

        //特殊群体管理
        Route::prefix('aged')->name('aged.')->group(function () {
            Route::get('/', 'AgedController@index')->name('index');
            Route::get('edit/{id}', 'AgedController@edit')->name('edit');
            Route::put('update/{id}', 'AgedController@update')->name('update');
            Route::get('create', 'AgedController@create')->name('create');
            Route::post('store', 'AgedController@store')->name('store');
            Route::delete('destroy/{id}', 'AgedController@destroy')->name('destroy');
        });

        //商户管理
        Route::prefix('mall')->name('mall.')->group(function () {
            Route::get('/', 'MallController@index')->name('index');
            Route::get('edit/{id}', 'MallController@edit')->name('edit');
            Route::put('update/{id}', 'MallController@update')->name('update');
        });
    });
});

resources/views/admin/buytop.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.index') }}">后台管理</a> / 消费排行</div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">用户名</th>
                                <th scope="col">手机号</th>
                                <th scope="col">消费金额</th>
                                <th scope="col">注册时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th scope="row">{{ $user->id}}</th>
                                    <th scope="row">{{ $user->name}}</th>
                                    <th scope="row">{{ $user->email}}</th>
                                    <th scope="row">￥{{ sprintf("%.2f",$user->total_money)}}</th>
                                    <th scope="row">{{ $user->created_at}}</th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
            {{ $users->links() }}
    </div>
@endsection

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.product',$mall->id) }}">商品管理</a> /
                        添加{{ $mall->name }}商品
                    </div>
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    <div class="card-body">
                        <form action="{{route('admin.store')}}" method="post" class="submit">
                            @csrf
                            <div class="form-group">
                                <label for="exampleInputPassword1">商品名称</label>
                                <input type="text" class="form-control" name="name" id="exampleInputPassword1" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword2">商品金额</label>
                                <input type="text" class="form-control" id="exampleInputPassword2" name="money"
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword2">库存数量</label>
                                <input type="text" class="form-control" id="exampleInputPassword2" name="stock"
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">商品描述</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="6"
                                          name="description"></textarea>
                            </div>
                            <div class="form-group">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="is_putaway" id="inlineRadio1"
                                           value="1" checked>
                                    <label class="form-check-label" for="inlineRadio1">上架</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="is_putaway" id="inlineRadio2"
                                           value="0">
                                    <label class="form-check-label" for="inlineRadio2">下架</label>
                                </div>
                            </div>
                            <input type="hidden" name="mall_id" value="{{ $mall->id }}">
                            <button type="submit" class="btn btn-primary submit-on">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.product',$mall->id) }}">商品管理</a> / 编辑{{ $mall->name }}商品</div>
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    <div class="card-body">
                        <form action="{{route('admin.update',$product->id)}}" method="post">
                            @csrf
                            @method('put')
                        <input type="hidden" name="mall_id" value="{{ $mall->id }}">
                            <div class="form-group">
                                <label for="exampleInputPassword1">商品名称</label>
                                <input type="text" class="form-control" name="name" id="exampleInputPassword1" value="{{ $product->name }}"  required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword2">商品金额</label>
                                <input type="text" class="form-control" id="exampleInputPassword2" name="money" value="{{ $product->money }}" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword2">库存数量</label>
                                <input type="text" class="form-control" id="exampleInputPassword2" name="stock" value="{{ $product->stock }}" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">商品描述</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="6" name="description"> {{$product->description}}</textarea>
                            </div>
                            <div class="form-group">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="is_putaway" id="inlineRadio1"
                                           value="1" @if($product->is_putaway==1) checked @endif>
                                    <label class="form-check-label" for="inlineRadio1">上架</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="is_putaway" id="inlineRadio2"
                                           value="0" @if($product->is_putaway==0) checked @endif>
                                    <label class="form-check-label" for="inlineRadio2">下架</label>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/findpassword.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.index') }}">后台管理</a></div>
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    <div class="card-body">
                        <form action="{{route('admin.findpassword')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">输入密码生成哈希</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" required name="password"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row">
            @if($s_admin)
            <div class="col-md-12" style="margin-bottom: 30px;">
                <div class="list-group">
                    <button type="button" disabled class="list-group-item list-group-item-action active">
                        系统管理
                    </button>
                    <a href="{{ route('admin.user.index') }}">
                        <button type="button" class="list-group-item list-group-item-action">用户管理</button>
                    </a>
                    <a href="{{ route('admin.userlog.index') }}">
                        <button type="button" class="list-group-item list-group-item-action">用户记录</button>
                    </a>
                    <a href="{{ route('admin.aged.index') }}">
                        <button type="button" class="list-group-item list-group-item-action">特殊关爱群体</button>
                    </a>
                    <a href="{{ route('admin.buytop') }}">
                        <button type="button" class="list-group-item list-group-item-action">消费排行</button>
                    </a>
                    <a href="{{ route('admin.mall.index') }}">
                        <button type="button" class="list-group-item list-group-item-action">商户管理</button>
                    </a>
                    <a href="{{ route('message.index') }}">
                        <button type="button" class="list-group-item list-group-item-action">建议&留言管理</button>
                    </a>
                    <a href="{{ route('admin.clear_cache') }}">
                        <button type="button" class="list-group-item list-group-item-action">清空所有缓存</button>
                    </a>
                </div>
            </div>
            @endif
            @foreach($malls as $mall)
                <div class="col-md-6" style="margin-bottom: 30px;">
                    <div class="list-group">
                        <button type="button" disabled class="list-group-item list-group-item-action active">
                            {{ $mall->name }}后台管理
                        </button>
                        <a href="{{ route('admin.product',$mall->id) }}">
                            <button type="button" class="list-group-item list-group-item-action">商品管理[{{ $mall->name }}]</button>
                        </a>
                        <a href="{{ route('admin.order',$mall->id) }}">
                            <button type="button" class="list-group-item list-group-item-action">订单管理[{{ $mall->name }}]</button>
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/admin/product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.index') }}">管理中心</a> / {{ $mall->name }}商品一览 / <a href="{{ route('admin.create',$mall_id) }}">添加商品</a></div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">商家名称</th>
                                <th scope="col">商品名称</th>
                                <th scope="col">套餐单价</th>
                                <th scope="col">商品描述</th>
                                <th scope="col">库存数量</th>
                                <th scope="col">是否上架</th>
                                <th scope="col">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <th scope="row">{{ $product->id }}</th>
                                    <th scope="row">{{ $product->mall->name }}</th>
                                    <td>{{ $product->name }}</td>
                                    <td>￥{{ $product->money }}</td>
                                    <td>{{ $product->description }}</td>
                                    <td>{{ $product->stock }}</td>
                                    <td>@if($product->is_putaway==1)<span class="badge badge-success">上架中</span>@else<span class="badge badge-danger">下架中</span>@endif</td>
                                    <td><a href="{{ route('admin.edit',['mall_id'=>$mall->id,'id'=>$product->id]) }}">编辑</a> /
                                        <a href="javascript:;"
                                           onclick="document.getElementById('product_{{$product->id}}').submit()">删除</a>
                                        <div style="display: none;">
                                            <form action="{{ route('admin.destroy',$product->id) }}" method="post"
                                                  id="product_{{ $product->id }}">
                                                <input type="hidden" name="mall_id" value="{{ $mall->id }}">
                                                @csrf
                                                @method('delete')
                                            </form>
                                        </div>
                                        /
                                        <a href="javascript:;"
                                           onclick="document.getElementById('product_up_putaway_{{$product->id}}').submit()">上架</a>
                                        <div style="display: none;">
                                            <form action="{{ route('admin.putaway',$product->id) }}" method="post"
                                                  id="product_up_putaway_{{ $product->id }}">
                                                <input type="hidden" name="is_putaway" value="1">
                                                @csrf
                                                @method('put')
                                            </form>
                                        </div>
                                        /
                                        <a href="javascript:;"
                                           onclick="document.getElementById('product_down_putaway_{{$product->id}}').submit()">下架</a>
                                        <div style="display: none;">
                                            <form action="{{ route('admin.putaway',$product->id) }}" method="post"
                                                  id="product_down_putaway_{{ $product->id }}">
                                                <input type="hidden" name="is_putaway" value="0">
                                                @csrf
                                                @method('put')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/total_order.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-12" style="margin-top: 10px;">
                <div class="card">
                    <div class="card-header"><a href="{{ route('admin.index') }}">管理中心</a> / <a href="{{ route('admin.order',$mall_id)  }}">订单管理</a> / {{ $mall_name }}商超报表
                    </div>
                    <div class="card-header">
                        <form action="" method="get">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="inputCity">下单开始日期</label>
                                    <input type="date" class="form-control" id="inputCity" name="c_start_date"
                                           value="{{ Request::input('c_start_date') }}">
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">下单结束日期</label>
                                    <input type="date" class="form-control" id="inputCity" name="c_end_date"
                                           value="{{ Request::input('c_end_date') }}">
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">收款开始日期</label>
                                    <input type="date" class="form-control" id="inputCity" name="p_start_date"
                                           value="{{ Request::input('p_start_date') }}">
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">收款结束日期</label>
                                    <input type="date" class="form-control" id="inputCity" name="p_end_date"
                                           value="{{ Request::input('p_end_date') }}">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">筛选</button>
                            <a href="{{ route('admin.total_order',$mall_id) }}"><button type="button" class="btn btn-primary btn-sm">重置</button></a>
                            <div style="float: right;">
                                <button type="button" class="btn btn-danger btn-sm" onclick="window.print();">打印本页
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">商品ID</th>
                                <th scope="col">商品名称</th>
                                <th scope="col">单价</th>
                                <th scope="col">数量</th>
                                <th scope="col">金额</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($final_products as $final_product)
                                <tr>
                                    <td>{{$final_product['product_id']}}</td>
                                    <td>{{$final_product['product_name']}}</td>
                                    <td>￥{{$final_product['product_price']}}</td>
                                    <td>{{$final_product['product_num']}}</td>
                                    <td>￥{{sprintf("%.2f",$final_product['product_num'] * $final_product['product_price'])}}</td>
                                </tr>
                            @endforeach
                            <tr>
                                <th scope="row">合计</th>
                                <td colspan="2"></td>
                                <th>{{ $products_total_num }}</th>
                                <th>￥{{ sprintf("%.2f",$products_total_money) }}</th>
                            </tr>
                            </tbody>
                        </table>
                        {{--                        {{ $orders->appends(['created_at' => Request::input('created_at'),'pay_date'=>Request::input('pay_date'),'pay_state'=>Request::input('pay_state'),'is_success'=>Request::input('is_success')])->links() }}--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection