routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//首页
Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

//个人中心
Route::get('/home', 'HomeController@index')->name('home');

//常用信息
Route::prefix('info')->name('info.')->group(function () {
    Route::get('/', 'InfoController@index')->name('index');
    Route::get('buy', 'InfoController@buy')->name('buy');
    Route::get('zb', 'InfoController@zb')->name('zb');
});

Route::middleware('auth')->group(function () {
    //地址管理
    Route::prefix('address')->name('address.')->group(function () {
        Route::get('/', 'AddressController@index')->name('index');
        Route::post('store', 'AddressController@store')->name('store');
        Route::delete('destroy/{id}', 'AddressController@destroy')->name('destroy');
    });

    //订单管理
    Route::prefix('order')->name('order.')->group(function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('create/{mall_id}', 'OrderController@create')->name('create');
        Route::post('store', 'OrderController@store')->name('store');
        Route::get('show/{id}', 'OrderController@show')->name('show');
        Route::post('success/{id}', 'OrderController@success')->name('success');
        Route::delete('destroy/{id}', 'OrderController@destroy')->name('destroy');
        Route::get('export_order/{id}', 'OrderController@export_order')->middleware('admin')->name('export_order');
    });
    //购物车
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::get('/{mall_id}', 'CartController@index')->name('index');
        Route::post('store', 'CartController@store')->name('store');
        Route::delete('destroy/{id}', 'CartController@destroy')->name('destroy');
    });
    //建议留言
    Route::prefix('message')->name('message.')->group(function () {
        Route::get('/', 'MessageController@index')->name('index')->middleware('admin');
        Route::get('create', 'MessageController@create')->name('create');
        Route::post('store', 'MessageController@store')->name('store');
        Route::delete('destroy/{id}', 'MessageController@destroy')->name('destroy')->middleware('s_admin');
    });
});

//后台管理
Route::prefix('admin')->middleware('auth', 'admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create/{mall_id}', 'AdminController@create')->name('create');
    Route::post('store', 'AdminController@store')->name('store');
    Route::get('edit/{mall_id}/{id}', 'AdminController@edit')->name('edit');
    Route::put('update/{id}', 'AdminController@update')->name('update');
    Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
    Route::post('pay', 'AdminController@pay')->name('pay');
    Route::post('pay_back', 'AdminController@pay_back')->name('pay_back');
    Route::get('product/{mall_id}', 'AdminController@product')->name('product');
    Route::get('order/{mall_id}', 'AdminController@order')->name('order');
    Route::post('trigger/{id}', 'AdminController@trigger')->name('trigger');
    Route::get('total_order/{mall_id}', 'AdminController@total_order')->name('total_order');
    Route::put('putaway/{id}', 'AdminController@putaway')->name('putaway');
    //订单回收站
    Route::prefix('recycle')->name('recycle.')->group(function () {
        Route::get('/{mall_id}', 'OrderRecycleController@index')->name('index');
        Route::post('back_order', 'OrderRecycleController@back_order')->name('back_order');
        Route::delete('destroy', 'OrderRecycleController@destroy')->name('destroy');
    });

    //以下操作需要超级管理员权限
    Route::middleware('s_admin')->group(function () {
        //清除所有缓存
        Route::get('clear_cache', 'AdminController@clear_cache')->name('clear_cache');
        //消费排行
        Route::get('buytop', 'AdminController@buytop')->name('buytop');


        //用户管理
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', 'UserController@index')->name('index');
            Route::get('edit/{id}', 'UserController@edit')->name('edit');
            Route::put('update/{id}', 'UserController@update')->name('update');
        });

        //用户记录管理
        Route::prefix('userlog')->name('userlog.')->group(function () {
            Route::get('/', 'UserLogController@index')->name('index');
        });

        //特殊群体管理
        Route::prefix('aged')->name('aged.')->group(function () {
            Route::get('/', 'AgedController@index')->name('index');
            Route::get('edit/{id}', 'AgedController@edit')->name('edit');
            Route::put('update/{id}', 'AgedController@update')->name('update');
            Route::get('create', 'AgedController@create')->name('create');
            Route::post('store', 'AgedController@store')->name('store');
            Route::delete('destroy/{id}', 'AgedController@destroy')->name('destroy');
        });

        //商户管理
        Route::prefix('mall')->name('mall.')->group(function () {
            Route::get('/', 'MallController@index')->name('index');
            Route::get('edit/{id}', 'MallController@edit')->name('edit');
            Route::put('update/{id}', 'MallController@update')->name('update');
        });
    });
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function mall()
    {
        return $this->belongsTo(Mall::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Mall;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (Auth::check()) {
            $malls = Cache::remember('malls', 86400 * 7, function () {
                return Mall::where('is_display',1)->get();
            });
            return view('home', compact('malls'));
        } else {
            return view('home.index');
        }
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Aged;
use App\Cart;
use App\Mall;
use App\Order;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use App\Exports\OrderExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Traits\CheckPermissions;

class OrderController extends Controller
{
    use CheckPermissions;

    //订单首页
    public function index()
    {
        $orders = Order::where('user_id', Auth::id())->OrderBy('created_at', 'DESC')->paginate(10);
        foreach ($orders as $key => $value) {
            $products = json_decode($value->products);
            foreach ($products as $k => $val) {
                $orders[$key]['pro_text'] .= '[' . $val->product->name . '×' . $val->total_num . ']';
            }
        }
        return view('home.order.index', compact('orders'));
    }

    //选购界面
    public function create($mall_id)
    {
        $mall = Cache::remember('mall_' . $mall_id, 86400, function () use ($mall_id) {
            return Mall::find($mall_id);
        });

        $this->check_result($mall);
        $is_admin=$this->is_mall_admin($mall_id);

        $address = Cache::remember('address_' . Auth::id(), 86400 * 7, function () {
            return Address::where('user_id', Auth::id())->get();
        });

        if ($address->count() == 0) {
            return redirect(route('address.index'))->with('success', '请先添加姓名、电话、楼栋号码再购物。');
        }

        if ($address->count() > 1) {
            return redirect(route('address.index'))->with('success', '您有多个收货信息，请删除多余的信息。【请务必保留含有楼栋号码的信息】');
        }

        if ($address->count() == 1) {
            $home_number = Cache::remember('address_first_' . Auth::id(), 86400 * 7, function () {
                return Address::where('user_id', Auth::id())->first()->home_number;
            });
            if ($home_number == '' || is_null($home_number)) {
                return redirect(route('address.index'))->with('success', '你没有完善楼栋号码，请完善后再购物。【删除收货信息重新填写】');
            }
        }

        //商品
        $products = Cache::remember('product_' . $mall_id, 30, function () use ($mall_id) {
            return Product::where('is_show', 1)->where('mall_id', $mall_id)->where('is_putaway', 1)->get();
        });

        return view('home.order.create', compact('products', 'mall','is_admin'));
    }

    //提交订单
    public function store(Request $request)
    {
        $mall_id = $request->input('mall_id');
        $is_show = Cache::remember('mall_' . $mall_id, 86400, function () use ($mall_id) {
            return Mall::find($mall_id);
        })->is_show;

        $is_admin=$this->is_mall_admin($mall_id);

        //管理员不受系统开关限制
        if (!$is_show && !$is_admin) {
            return back()->with('success', '系统已经关闭,订单提交失败!!!');
        }
        $carts = Cart::where('user_id', Auth::id())->where('mall_id', $mall_id)->get();
        if ($carts->count() == 0) {
            return back()->with('success', '购物车为空,订单提交失败!!!');
        }

        //购物车总金额
        try {
            $total_price = 0;
            foreach ($carts as $key => $value) {
                $total_price += $value->product->money * $value->total_num;
            }
        } catch (\Exception $exception) {
            return back()->with('success', '您的购物车中有失效的商品,请删除后重新提交订单!!!');
        }

        $is_admin = $this->is_mall_admin($mall_id);

        //是否为代买模式 只允许管理员代买
        $aged_id = $request->input('aged_id');
        if ($aged_id != 0 && $is_admin) {
            $address = Aged::find($aged_id);
            $data['name'] = $address->name;
            $data['tel'] = $address->tel;
        } else {
            $address = Address::where('user_id', Auth::id())->first();
            $data['name'] = $address->name;
            $data['tel'] = $address->tel;
        }

        $data['user_id'] = Auth::id();
        $data['products'] = json_encode($carts->toArray());
        $data['total_money'] = $total_price;
        $data['total_num'] = array_sum($carts->pluck('total_num')->toArray());
        $data['mall_id'] = $mall_id;
        try {
            $order = DB::transaction(function () use ($data, $mall_id, $carts) {
                //创建订单
                $order = Order::create($data);
                //减商品对应的库存
                foreach ($carts as $cart) {
                    $product = Product::lockForUpdate()->find($cart->product_id);
                    $product->decrement('stock', $cart->total_num);
                    //如果库存为负数则抛出异常
                    if ($product->stock < 0) {
                        throw new \Exception('当前商品' . $product->name . '库存不足，提交订单失败!');
                    }
                }
                //清空购物车
                Cart::where('user_id', Auth::id())->where('mall_id', $mall_id)->delete();
                return $order;
            }, 5);
        } catch (\Exception $exception) {
            return back()->with('success', '提交订单失败!!!!!' . $exception->getMessage());
        }
        return redirect(route('order.show', $order->id))->with('pay_success', '提交订单成功');
    }

    //显示订单
    public function show($id)
    {
        $order = Order::with('mall')->where('user_id', Auth::id())->where('id', $id)->first();
        $products = json_decode($order->products);
        $pro_text = null;
        foreach ($products as $key => $value) {
            $pro_text .= '[' . $value->product->name . '×' . $value->total_num . ']';
        }
        return view('home.order.show', compact('order', 'pro_text'));
    }

    //确认收货
    public function success(Request $request, $id)
    {
        //是否是管理员操作
        if (Auth::user()->is_admin !== '0') {
            $order = Order::find($id);
            $mall_id = $order->mall_id;
            $this->is_mall_manager($mall_id);
        } else {
            $order = Order::where('user_id', Auth::id())->find($id);
        }

        if (is_null($order->pay_time)) {
            return back()->with('success', '确认收货失败！此订单未付款。如果您已经付款，请联系商家确认收款！');
        }
        $update = $order->update(['is_success' => 1]);

        if ($update) {
            return back()->with('success', '确认收货成功!');
        } else {
            return back()->with('success', '确认收货失败!!!!!');
        }
    }

    //删除订单
    public function destroy(Request $request, $id)
    {
        //判断是否从后台发起删除请求
        $order = Order::find($id);
        $is_admin = $request->input('is_admin');
        $mall_id = $order->mall_id;

        //如果是管理员删除 需要检查权限;
        if ($is_admin || ($order->user_id != Auth::id())) {
            $this->is_mall_manager($mall_id);
        }

        if (is_null($order)) {
            return back()->with('success', '订单不存在,可能已经被删除了!!!!');
        }
        //订单未支付并且未收货
        if (is_null($order->pay_time) && $order->is_success === 0) {
            $del = DB::transaction(function () use ($id, $order) {
                $products = json_decode($order->products, true);
                foreach ($products as $product) {
                    $this_product = Product::find($product['product']['id']);
                    //商品存在并且是当天删除的情况下还库存
                    if (!is_null($this_product) && (date("Y-m-d", strtotime($order->created_at)) == date("Y-m-d"))) {
                        $this_product->increment('stock', $product['total_num']);
                    }
                }
                //删除订单
                return Order::destroy($id);
            });

            //删除成功
            if ($del) {
                if ($is_admin) {
                    return back()->with('success', '订单删除成功!');
                }
                return redirect(route('order.index'))->with('success', '订单删除成功!');
            }

            //删除失败
            if (!$del) {
                return back()->with('success', '订单删除失败!!!!!');
            }

        } else {
            return back()->with('success', '订单已经支付或者已经收货，无法删除！！！');
        }
    }

    //导出订单
    public function export_order(Request $request, $id)
    {
        $mall_id = $id;
        $this->is_mall_manager($mall_id);
        $s_id = array();
        if ($request->input('s_id') != '') {
            $s_id = function ($query) use ($request) {
                $query->where('id', $request->input('s_id'));
            };
        }

        //按收货人姓名搜索
        $s_name = array();
        if ($request->input('s_name') != '') {
            $s_name = function ($query) use ($request) {
                $query->where('name', $request->input('s_name'));
            };
        }

        //按收货人电话搜索
        $s_tel = array();
        if ($request->input('s_tel') != '') {
            $s_tel = function ($query) use ($request) {
                $query->where('tel', $request->input('s_tel'));
            };
        }

        //按创建时间搜索
        $c_time = array();
        if ($request->input('created_at') != '') {
            $c_date = str_replace(' ', '', $request->input('created_at'));
            $start_c_date = explode('~', $c_date)[0];
            $end_c_date = explode('~', $c_date)[1];
            $c_time = function ($query) use ($start_c_date, $end_c_date) {
                $query->whereDate('created_at', '>=', $start_c_date)->whereDate('created_at', '<=', $end_c_date);
            };
        }

        //按支付时间搜索
        $p_time = array();
        if ($request->input('pay_date') != '') {
            $p_date = str_replace(' ', '', $request->input('pay_date'));
            $start_p_date = explode('~', $p_date)[0];
            $end_p_date = explode('~', $p_date)[1];
            $p_time = function ($query) use ($start_p_date, $end_p_date) {
                $query->whereDate('pay_time', '>=', $start_p_date)->whereDate('pay_time', '<=', $end_p_date);
            };
        }

        //按支付状态搜索
        $p_state = array();
        if ($request->input('pay_state') == 'y') {
            $p_state = function ($query) use ($request) {
                $query->whereNotNull('pay_time');
            };
        }

resources/views/home/order/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        @if($mall->is_show==0)
            <div class="alert alert-danger" role="alert">
                {{ $mall->name }}当前休息中，你可以逛逛其他商家。
            </div>
        @endif
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">个人中心</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ $mall->name }}</li>
                <li class="breadcrumb-item"><a href="{{ route('cart.index',$mall->id) }}">我的购物车</a></li>
            </ol>
        </nav>
        <div class="row">
            @foreach($products as $product)
                <div class="col-md-4">
                    <div class="card" style="width: 20rem; margin: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ $product->name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">￥{{ $product->money }}
                                剩余库存：{{ $product->stock }}</h6>
                            <div class="form-group">
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="10"
                                          disabled>{{ $product->description }}</textarea>
                            </div>
                            <form action="{{route('cart.store')}}" method="post" class="submit">
                                @csrf
                                <input type="hidden" name="product_id" value="{{ $product->id }}">
                                <input type="hidden" name="mall_id" value="{{ $mall->id }}">
                                <input type="hidden" name="num" value="1">
                                @if($mall->is_show==0)
                                    <button type="button" class="btn btn-warning" disabled>
                                        商家休息中...
                                    </button>
                                    @if($is_admin)
                                        <button type="submit" class="btn btn-danger submit-on" >√
                                        </button>
                                    @endif
                                @endif
                                @if($mall->is_show==1)
                                    @if($product->stock <= 0)
                                        <button type="button" class="btn btn-secondary" disabled>卖完了...</button>
                                    @else
                                        <button type="submit" class="btn btn-danger submit-on">
                                            加入购物车
                                        </button>
                                    @endif
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/home/order/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">个人中心</a></li>
                <li class="breadcrumb-item active" aria-current="page">我的订单</li>
            </ol>
        </nav>
        <div class="row ">
            @foreach($orders as $order)
                <div class="col-md-4">
                    <div class="card" style="width: 92%; margin: 10px;">
                        <div class="card-header">
                            <span class="order_id" style="cursor: pointer;" data-show="1"
                                  data-order="{{ $order['id'] }}">订单号:{{ $order['id'] }}</span>
                            收货人:{{ $order['name'] }} {{ $order['tel'] }}
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-4">{{  $order['pro_text'] }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">共{{ $order['total_num'] }}件
                                ￥{{ $order['total_money'] }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">下单时间 {{ $order['created_at'] }}</h6>
                            <span class="badge badge-danger"
                                  style="margin-right: 5px;font-size: 85%!important;">商家：{{ $order['mall']->name }}</span>
                            @if(is_null($order['pay_time']))
                                <span class="badge badge-warning" style="font-size: 85%!important;">未付款</span>
                            @else
                                <span class="badge badge-success" style="font-size: 85%!important;">已付款</span>
                            @endif
                        </div>
                        <div class="card-footer bg-transparent ">
                            @if($order['is_success']===0)
                                @if(is_null($order['pay_time']))
                                    <button type="button" class="btn btn-danger btn-sm"
                                            style="float:left;margin-right: 10px;" data-toggle="modal"
                                            data-target="#order_pay_{{ $order->id }}">立即付款
                                    </button>
                                @else
                                    <form action="{{ route('order.success',$order['id']) }}" method="post"
                                          style="float:left;margin-right:10px;">
                                        @csrf
                                        <input type="hidden" name="order_id" value="{{ $order['id'] }}">
                                        <button type="submit" class="btn btn-primary btn-sm">确认收货</button>
                                    </form>
                                @endif
                                @if(is_null($order['pay_time']))
                                    <form action="{{ route('order.destroy',$order['id']) }}" method="post"
                                          style="float:left;margin-right: 10px;">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-dark btn-sm">删除订单</button>
                                    </form>
                                @endif
                            @else
                                <button type="button" class="btn btn-success btn-sm" disabled style="cursor: default;">
                                    已经收货
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <hr>
        {{ $orders->links() }}
    </div>

    @foreach($orders as $order)
        <div class="modal fade" id="order_pay_{{ $order->id }}" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="order_success" aria-hidden="true">
            <div class="modal-dialog modal-sm " role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">付款方式</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <img src="{{$order->mall->pay_qrcode}}" class="card-img-top img-responsive center-block">
                            <div class="card-body">
                                <h6 class="card-title">加好友付款需知</h6>
                                <p class="card-text">订单号+姓名+电话+金额 然后转账</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
                    </div>
                </div>
            </div>
        </div>
    @endforeach

    {{--勿泄露订单号的提示--}}
    <div class="modal fade" id="danger_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-danger" id="exampleModalLabel">重要提醒</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>我们的唯一取货凭证是订单号和姓名，请务必不要外传，否则会有商品被冒领的风险！！！</p>
                    <p>如果需要截图并发送到微信群，您可以点击订单号将订单号隐藏再发送。</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">我就不听</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="order_alert">别说了我知道了
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(function () {
            //点击显示隐藏订单号
            $(".order_id").click(function () {
                let data_show = $(this).data("show");
                if (data_show === 1) {
                    let num = $(this).data("order");
                    localStorage.setItem('order' + num, num);
                    $(this).text('订单号:****');
                    $(this).data("show", 0);
                    return false;
                }
                if (data_show === 0) {
                    let num = $(this).data("order");
                    $(this).text('订单号:' + localStorage.getItem('order' + num));
                    $(this).data("show", 1);
                    localStorage.removeItem('order' + num);
                    return false;
                }
            });

            //弹出不要泄露订单号的提示
            let order_alert = localStorage.order_alert;
            if (order_alert != 1) {
                $("#danger_modal").modal().show();
            }
            $("#order_alert").click(function () {
                localStorage.order_alert = 1;
            })
        })
    </script>
@endsection